version: '3'
services:
  db:
    image: mysql:8.0.34
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: foody
    ports:
      - "3306:3306"
  my-spring-app:
    build: .
    depends_on:
      - db
    container_name: back-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/foody?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: prod

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_PW: ${GOOGLE_CLIENT_PW}
    ports:
      - "8082:8082"
