spring:
  datasource:
    url: jdbc:h2:mem:foody
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_PW}
            scope:
              - email
              - profile
  cache:
    type: redis
    redis:
      time-to-live: 3600 # 데이터 유지 시간
      cache-null-values: false # NUll 캐싱 여부
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

jwt:
  token:
    secret: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
