spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foody?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_PW}
            scope:
              - email
              - profile
jwt:
  token:
    secret: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
